"""
Django settings for greenai_hub project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
from .env import env_verifier, credentials

env_verifier(credentials)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = credentials.get('django_secret_key', '8rcb76296508273yt0827y3w64v357')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = credentials.get('debug', False)

ALLOWED_HOSTS = credentials.get('allowed_hosts', [])

CSRF_TRUSTED_ORIGINS = [
    'https://sandbox.e-n.live',
    'http://localhost',
    'http://127.0.0.1',
]

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "https://sandbox.e-n.live"
]

CORS_ALLOW_CREDENTIALS = True

BASE_URL = credentials.get('base_url')


# Application definition

INSTALLED_APPS = [
    'allauth',
    'allauth.account',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'django_filters',
    'rest_framework_api_key',
    'rest_framework',
    'corsheaders',
    'drf_yasg',

    'user', 
    'dashboard',
    'detecter',
    'analytics',
    'ai_assistent',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

AUTHENTICATION_BACKENDS = [
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend'
]

ROOT_URLCONF = 'greenai_hub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'greenai_hub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': credentials.get('db_name'),
#         'USER': credentials.get('db_user'),
#         'PASSWORD': credentials.get('db_password'),
#         'HOST': credentials.get('db_host'),
#         'PORT': '5432',
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

SWAGGER_SETTINGS = {
    'SECURITY_DEFINITIONS': {
        'Api-Key': {
            'type': 'apiKey',
            'name': 'Authorization',
            'in': 'header',
            'description': 'API Key Authorization header using the Api-Key scheme. Example: "Authorization: Api-Key {token}"'
        }
    },
    'DEFAULT_INFO': 'path.to.urls.api_info',
    'USE_SESSION_AUTH': True,
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework_api_key.permissions.HasAPIKey',
    )
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# Static files configuration
STATIC_URL = '/static/'
# Keep your in-repo `static/` directory in STATICFILES_DIRS so the dev server
# and collectstatic can find assets like fontawesome and ckeditor.
# Do NOT set STATIC_ROOT to the same directory as your source `static/` or
# collectstatic may overwrite source files. Use a separate folder for the
# collected output.
STATICFILES_DIRS = [
    BASE_DIR / 'assets',
    # BASE_DIR / 'static',
]
# Directory where `collectstatic` will gather files for production
STATIC_ROOT = BASE_DIR / 'collected_static'

# Media files configuration
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Django all-auth settings
ACCOUNT_USER_MODEL_USERNAME_FIELD = 'email'  # Tell allauth to use email field
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_UNIQUE_EMAIL = True


ACCOUNT_SESSION_REMEMBER = True
SESSION_COOKIE_AGE = 60 * 60 * 24 * 30  # 30 days in seconds


# If your custom user model doesn't have a username field, keep this as None
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory' #'optional' 
ACCOUNT_ADAPTER = 'user.adapters.NoSignupAccountAdapter'
ACCOUNT_EMAIL_SUBJECT_PREFIX = ''  # Remove the [site] prefix from email subjects


# Redirect urls
LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'dashboard:index'  # Redirect to dashboard home after login
LOGOUT_REDIRECT_URL = 'account_login'

# Email configuration from credentials
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

# or, if you want to inspect programmatically from shell
# EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"

EMAIL_HOST = credentials.get('email_host', 'localhost')
EMAIL_PORT = int(credentials.get('email_port', 25))
EMAIL_HOST_USER = credentials.get('email_host_user', '')
EMAIL_HOST_PASSWORD = credentials.get('email_host_password', '')
EMAIL_USE_TLS = True if int(credentials.get('email_port', 0)) == 587 else False


# Other configurations
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'user.User'
WSGI_APPLICATION = 'greenai_hub.wsgi.application'
ROOT_URLCONF = 'greenai_hub.urls'
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Kolkata'
USE_I18N = True
USE_TZ = True
DATA_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024  # 30 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 30 * 1024 * 1024  # 30 MB


# Sites framework: set the ID of the current Site (create one in DB with this PK)
SITE_ID = 1